### ISSUE TITLE
Error communicating with Domotiga

### ISSUE THREAD

**Issue by ram1505** [Samfox2/homebridge-domotiga#1]
Hi,
I just installed your homebridge plugin and while trying to use the plugin, on my iPhone Homebridge app, I get error saying error communicating. I've made sure the server and port number are correct. Not sure whats going wrong. Can you please help?

**Comment by Samfox2** [comment]
Hi, could you please post your homebridge console output after starting?

**Comment by ram1505** [comment]
Hey, sorry I forgot to update here. It worked finally.
