### ISSUE TITLE
Doors and windows control

### ISSUE THREAD

**Issue by fjaraujo** [Samfox2/homebridge-domotiga#10]
Hi Sandfox,
thanks to homebridge-domotiga, I am controlling from homekit doors and windows (blinds), but as "switch" devices. So speaking with Siri I have to use the sentence "Switch on the door" or "Switch off the window", which is quite strange. 

How can these devices managed as doors and windows in order to enable the right instructions for Siri?

Thanks in advance

**Comment by Samfox2** [comment]
Home app only allowes to change the type of switches to Light/Fan/Switch. The plugin has to be extended to support doors and blinds. I see what I can do but as usually, time is limited...

**Comment by Samfox2** [comment]
Ok, I added basic support for doors, windows and window covering. Percentage values are mapped to 0=closed and everything else to 1= open.
You could try it by copying index.js into your plugin folder...

**Comment by fjaraujo** [comment]
Great! Thanks very much! I will try it this evening and keep you updated!

Regards
Javier.

2017-01-18 10:30 GMT+01:00 Samfox2 <notifications@github.com>:
