### ISSUE TITLE
Question - do you get the notifications on more than one device?

### ISSUE THREAD

**Issue by brownad** [Samfox2/homebridge-domotiga#13]
I am only receiving on a single iOS device the other two never receive it

**Comment by Samfox2** [comment]
It should work for every icloud connected device. Maybe the device that doesn't receive notifications needs to be reconnected (signout/signin)?

**Comment by brownad** [comment]
I'll try that thanks

Sorry wrong repo for the issue question meant the other one.

Btw you've seen it work on the home screen with the View swipe? Looks amazing thanks for the doorbell help

**Comment by Samfox2** [comment]
Yes, nice to have access right from home screen.

**Comment by brownad** [comment]
Tried to sign out and in didn't change. Strangely sensors like smoke do push to all devices
