### ISSUE TITLE
Number of mapped devices : undefined

### ISSUE THREAD

**Issue by nordblick2** [Samfox2/homebridge-domotiga#15]
The message will print out on right after start. I guess, it should not be "undefined", but  i was not able to track that down to the underlying reason (i need some more time with 2.0 code ;))

Message comes from line 192 - could be more or less (due to some local changes on my side)

**Comment by Samfox2** [comment]
It tells you that no accessories are configured. 
You could add an additionel check like 
`if (nod) {………}` 
I thought this wouldn't be neccessary as there should allways at least 1 defined.
