### ISSUE TITLE
NO issue, just a discussion around the plugin

### ISSUE THREAD

**Issue by nordblick2** [Samfox2/homebridge-domotiga#16]
Hey Samfox2,
im not really familiar with the domotiga backend (and i'm not planning use it) but i have some question (not really an issue, but i didnt found a better way to get in contact or to discuss some things around your plugin). 

Sometimes, the plugin uses integer values for device states (0 or 1), sometimes strings (On and Off). Is that a dependency from the domotiga backend? Is there a way to use always integer or boolean values for such states? Would be a bit easier. However, I already implemented that in my fork but before i'll send a larger pull request in some days (or later haha), i would like to ensure compatibility with domotiga backend...

In addition: What do you think about some "build in" sensors for raspberry's temperature, that could be enables with just two single config-line (e.g. {"service":"rpi.sysmonitor","name": "Whatever"}) and could contain some temperature warnings (just implemented that in my fork as well)? I'm using that plugin on a BSD but the command interface is already implemented and it would just be a nice feature... Not sure if the domotiga community needs/whats that...

Cheers,
nordblick

**Comment by Samfox2** [comment]
Hi nordblick,
Good to hear that you make progress.
DomotiGa is quiet flexible regarding value types so you can have both on/off or 1/0. maybe an additional config parameter would solve the problem.
Support for build in sensors of rpi could be useful but optional as you can run homebridge on any machine. I'm using the homebridge-cmd plugin for getting the system temperature.

**Comment by nordblick2** [comment]
Sure, it should be optional. I will think about  ;)
