### ISSUE TITLE
Error after upgrade to 2.0

### ISSUE THREAD

**Issue by dahl1632** [Samfox2/homebridge-domotiga#18]
Hello, after upgrade to the new 2.0 i get the following error message:

[2017-02-11 21:38:49] ERROR LOADING PLUGIN homebridge-domotiga:
[2017-02-11 21:38:49] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

2017-02-11 21:38:49] No plugins found. See the README for information on installing plugins.
[2017-02-11 21:38:49] Loaded config.json with 0 accessories and 1 platforms.
[2017-02-11 21:38:49] ---
[2017-02-11 21:38:49] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Domotiga' was not registered by any plugin.

**Comment by Samfox2** [comment]
Seems like your node version is too old. Please uncomment "use strict"; in index.js of homebridge-domotiga plugin and try again.

**Comment by dahl1632** [comment]
Thanks for quick answear. I did that but got:
/usr/local/lib/node_modules/homebridge-domotiga/index.js:20
    EvePowerConsumption = function () {
                        ^

ReferenceError: EvePowerConsumption is not defined

Tried to upgrade to nodejs 4.7.3. Same problem.

**Comment by Samfox2** [comment]
Hmm, you need at least node 6.x, please try to update...

**Comment by dahl1632** [comment]
Hmm, still not working.
dahl@bjd-srv-3:~/.homebridge$ node -v
v6.9.5
dahl@bjd-srv-3:~/.homebridge$ npm -v
4.3.0

Uncommented use strict in index.js - homebridge-domotiga dir. But still: 
[2017-02-12 10:34:30] Loaded plugin: homebridge-domotiga
homebridge API version: 2.1
/usr/local/lib/node_modules/homebridge-domotiga/index.js:20
    EvePowerConsumption = function () {
                        ^

ReferenceError: EvePowerConsumption is not defined

Any other idea? :)

**Comment by Samfox2** [comment]
Is it working without eve custom services?

**Comment by dahl1632** [comment]
I can try. How do i disable eve custom service?

**Comment by Samfox2** [comment]
Just do not define any eve characteristic in config.json (like powermeter).

**Comment by dahl1632** [comment]
Okey, i only got one device in my config.json, a temperature unit:

#cat config.json
{
    "bridge": {
        "name": "HomebridgePI",
        "username": "A3:22:3D:DE:BA:BE",
        "port": 51826,
        "pin": "031-45-156"
    },

    "description": "The Onion!",

    "platforms": [
        {
            "platform": "Domotiga",
            "name": "Domotiga",
            "host": "172.16.22.7",
            "port": "9090",
            "devices": [

                {
                    "name": "Badrum 1",
                    "service": "TemperatureSensor",
                    "manufacturer": "DIY",
                    "model": "TinyTX",
                    "device": "471",
                    "valueTemperature": "1",
                    "valueHumidity": "2",
                    "polling": true,
                    "pollInMs": "1000"
                }
            ]
        }
    ],

    "accessories": [ ]
}

**Comment by dahl1632** [comment]
Any idea? I tried to remove my whole homekit settings in iOS and remove persist folder. Reinstalled npm. Nothing works :(

**Comment by nordblick2** [comment]
Edit: the described way addresses the last comment from dahl1632 only

I had some similar issue some days ago: My second iOS device found the bridge without problems, but my iPhone didn't. I was so frustrated, that i reinstalled  iOS completely - *without any change*.  In the end i just changed the bridge's name to something else and "fixed" my problem. Have you tried that already?

For me it seems that some caching issue was the underlying reason (i have a similar problem  for accessories/devices as well - changing properties changes nothing, but renaming works. After renaming and restarting i can re-set the only name back  ;)

**Comment by Samfox2** [comment]
Fixed (finally)
