### ISSUE TITLE
Window Covering do not stop at open action

### ISSUE THREAD

**Issue by fjaraujo** [Samfox2/homebridge-domotiga#19]
Hi, once I configured a windowcovering, as value2, I have added domotiga events to change value1 to "On" or "Off"  (my coverings do not support 1-0 values, are controlled with X10).

This mechanism works ok, but in homekit the button remains at "Openning...". But the close operation works ok.

The log says: "Persiana: successfully set window covering position to 100"

Thanks
Javier

**Comment by Samfox2** [comment]
Works now with latest commit.
