### ISSUE TITLE
Service.Lightbulb support

### ISSUE THREAD

**Issue by gurtjun** [Samfox2/homebridge-domotiga#24]
I currently have a setup with a Velbus [VMBDMI](https://www.velbus.eu/products/view/?id=386050&lang=nl) module which I use to dim my lights. 
I'm using a `Switch` type for this device with `valueSwitch` set to value 1 in my homebridge configuration file.

I'm not able to dim my lights because the values of a Switch can only be `On` or `Off`. I can see the following values for my device in Domotiga (value1):
- Off (when light is turned off)
- On (when light is turned on)
- Dim 75 (when dimming percentage is set to 75 with Homecenter)

I think it would be useful to add support for `Service.Lightbulb` which has an optional characteristic `Characteristic.Brightness`. 

Let me know if I can help you out with this.

**Comment by nordblick2** [comment]
Hey gurtjun (and samfox2),
i implemented that already in my fork of samfox2's repository. I try to keep in parallel with his most recent version, but didn't hat time to implement some changes he made within last weeks. I hope I can do that it in the next weeks, update my some docu, and provide a pull request. 

@Samfox2 Seems hard to get in *direct* contact with you :). I'm not really aware of some dependencies regarding domotica (e.g. your code accept some a "1", sometimes there was "On" or "true" - I unified that in my fork. I implemented some other features as well (like various backend like url, local commands or file interface). I don't use domotica at all, so I can't run a full compatibility test in any way.  So... pull request could be hard to accept :)

**Comment by Samfox2** [comment]
Sorry, I am quite busy at the moment :-) Would be really cool if you could implement your changes into the plugin.

**Comment by gurtjun** [comment]
Hi @nordblick2,

Cool you already implemented the possibility to add a `Lightbulb`. Not sure if it's going to work with Domotiga though. E.g. you're using the below function call to get a value from Domotiga:
```
...
self.domotigaGetValue(thisDevice, "brightness", function (error,value) {
...
```

As far as I'm aware you can only get values by their number, correct me if I'm wrong @Samfox2? In Domotiga they are represented as `value1`, `value2`, `value3`, etc... 
So I don't think `"brightness"` will work as a value. But I'm not that experienced either with Domotiga so I could be wrong...

**Comment by Samfox2** [comment]
@gurtjun yes that‘s right, the column of all 3 values have to be defined in config.json

**Comment by brefra** [comment]
Thanks to the example in the fork of @nordblick2. I've just created pull request #26 that contains the required functionality. Both switching and dimming a light bulb.

**Comment by Samfox2** [comment]
Merge it right now, thank you.
