### ISSUE TITLE
Error: The requested platform 'Domotiga' was not registered by any plugin.

### ISSUE THREAD

**Issue by leeroyc01** [Samfox2/homebridge-domotiga#30]
Hi, Recently installed this and when I restart homebridge I get the above error.  I've tried changing config.json but still getting the same error.  Interestingly when I remove the config.json entries I can see the domotiga plugin loading.
 Any thoughts please?

**Comment by Samfox2** [comment]
Could you please post your config.json file?

**Comment by leeroyc01** [comment]
thanks.  I sorted the problem by changing the config.json to DomotiGa rather than Domotiga.  Seems to have sorted it
