### ISSUE TITLE
Static match on numbers not working for me

### ISSUE THREAD

**Issue by Schouwenburg** [Samfox2/homebridge-domotiga#4]
Hello, first of all thanks for the great job! Furthermore I ran into a problem. On line 169 of index.js you match on the first level of the json data blob for number 37 (if (i == 37) ..). In my installation this should be 38. Better would be to match on the right key instead of the nth number. Same for the level two and three matches. Best, Janno

**Comment by Samfox2** [comment]
You are right, please feel free to make any change.

**Comment by Samfox2** [comment]
Should be fixed now...
