### ISSUE TITLE
Keep sync with iOS devices

### ISSUE THREAD

**Issue by fjaraujo** [Samfox2/homebridge-domotiga#5]
Hi Samfox,

I have installed the plugin and works ok, I can send commands from iOS to Domotiga. And when home app starts, the status of the devices is updated. But if I change the state in Domotiga, home app doesn't update...

Is there some way to solve this?

Thanks!

**Comment by Samfox2** [comment]
Hi,

the only thing I could imagine to solve this problem would be polling.

**Comment by fjaraujo** [comment]
Yes, or maybe sending a message from Domotiga once a change is detected, could be?

Thanks

**Comment by Samfox2** [comment]
Ok, added optional polling for switches.
