### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by lolouk44** [Samfox2/homebridge-domotiga#7]
Hi Samfox2,

Not sure how, but I finally managed to sync eve with Domotiga again after upgrading to iOS10 (for some reason it would no longer work).
Only issue now is that I get error messages any time I try to change the state of a switch:

`[Kitchen Door] getting SwitchState for Kitchen Door
[Kitchen Door] Sorry err:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
[Kitchen Door] getSwitchOn GetValue failed: connect ECONNREFUSED
[Kitchen Window] getting SwitchState for Kitchen Window
[Kitchen Window] Sorry err:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
[Kitchen Window] getSwitchOn GetValue failed: connect ECONNREFUSED
[Kitchen Door] Setting SwitchState for 'Kitchen Door' to 1
[Kitchen Door] Sorry err:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
[Kitchen Door] Error setting switch state to 1 on the 'Kitchen Door'
`

I tried to change 37 to 38 as per [issue #4], to no avail. 
Any idea?

**Comment by Samfox2** [comment]
Please try with the new update...

**Comment by lolouk44** [comment]
Yup, fixed, thanks :)
